name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: changeDirectory
      run: cd hexlet-my-first-workflow
      
    - name: say-hello
      run: make say-hello
